# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-lts-latest
  tools:
    nodejs: "22"
  jobs:
    install:
      - npm install vitepress --force
    build:
      html:
        # The site was created by running `vitepress init`
        # and following the official guide
        # https://vitepress.dev/guide/getting-started
        - vitepress build docs
        - mkdir -p $READTHEDOCS_OUTPUT/
        - mv docs/.vitepress/dist $READTHEDOCS_OUTPUT/html
