approvedGitRepositories:
  - "**"

compressionLevel: mixed

enableScripts: true

logFilters:
  - level: discard
    pattern: "*(paf38f)*"
  - level: discard
    pattern: "*(p741fc)*"

nodeLinker: node-modules
